story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story5/', include('story5.urls')),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.index, name='index'),
    path('Profile/', views.profile, name='Profile'),
    path('hobbies/', views.hobbies , name = 'hobbies'),
    path('comingsoon/', views.comingsoon, name = 'comingsoon'),
    path('story-1/', views.story1, name = 'story1'),
    path('navmenu/', views.navmenu, name = 'navmenu')
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('<int:pk>/', views.delete, name = 'erase'),
    path('detail/<int:pk>',views.detail, name = "detail")
]

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

class matkul(models.Model):
    nama = models.CharField(max_length = 200)
    dosen = models.CharField(max_length = 200)
    sks = models.IntegerField()
    deskripsi = models.CharField(max_length =1000)
    sem_tahun = models.CharField(max_length = 200)
    ruang_kelas = models.CharField(max_length = 200)

story5/forms.py
from django import forms

class matakuliah(forms.Form):
       fields = ["namamatkul", "dosen","sks","deskripsi","tahun","ruangan"]
       error_messages = { "required": "masih kosong"}
       input_nama = {"type": "text", "placeholder":"nama matkul"}
       input_dosen = {"type": "text", "placeholder":"nama dosen"}
       input_sks = {"type": "Integer", "placeholder":"jumlah sks"}
       input_desc = {"type": "text", "placeholder":"deskripsi matkul"}
       input_tahun = {"type": "text", "placeholder":"tahun ajar"}
       input_kelas = {"type": "text", "placeholder":"ruang kelas"}
       
       namamatkul = forms.CharField(required = True,max_length=200, widget = forms.TextInput(attrs=input_nama))
       dosen = forms.CharField(required = True ,max_length = 200,widget = forms.TextInput(attrs=input_dosen))
       sks = forms.IntegerField(required = True, widget = forms.TextInput(attrs=input_sks))
       deskripsi = forms.CharField(required = True,max_length =1000,widget = forms.TextInput(attrs=input_desc))
       sem_tahun = forms.CharField(required = True, max_length = 200, widget = forms.TextInput(attrs=input_tahun))
       ruang_kelas = forms.CharField(required = True,max_length = 200, widget = forms.TextInput(attrs=input_kelas))

story4/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'Profile.html')

def hobbies(request):
    return render(request, 'hobbies.html')

def story1(request):
    return render(request, 'story-1.html')

def comingsoon(request):
    return render(request, 'comingsoon.html')

def navmenu(request):
    return render(request, 'navmenu.html')

story5/views.py
from django.shortcuts import redirect, render
from . import forms,models 

def jadwal(request):
    if request.method == "POST":
        formulir = forms.matakuliah(request.POST)
        if formulir.is_valid():
            subjects = models.matkul()
            subjects.nama = formulir.cleaned_data["namamatkul"]
            subjects.dosen = formulir.cleaned_data["dosen"]
            subjects.sks = formulir.cleaned_data["sks"]
            subjects.deskripsi = formulir.cleaned_data["deskripsi"]
            subjects.sem_tahun = formulir.cleaned_data["sem_tahun"]
            subjects.ruang_kelas = formulir.cleaned_data["ruang_kelas"]
            subjects.save()
        return redirect("/story5")
    else:
        form = forms.matakuliah()
        jadwal = models.matkul.objects.all()
        form_dict = {'formulir' : form,'jadwal' : jadwal}
    return render(request, 'jadwal.html', form_dict)

def detail(request, pk):
    jadwal = models.matkul.objects.get(id=pk)
    details ={'jadwal': jadwal}
    return render(request, 'detail.html',details)


def delete(request,pk):
    if request.method == "POST":
        formulir = forms.matakuliah(request.POST)
        if formulir.is_valid():
            subjects = models.matkul()
            subjects.nama = formulir.cleaned_data["namamatkul"]
            subjects.dosen = formulir.cleaned_data["dosen"]
            subjects.sks = formulir.cleaned_data["sks"]
            subjects.deskripsi = formulir.cleaned_data["deskripsi"]
            subjects.sem_tahun = formulir.cleaned_data["sem_tahun"]
            subjects.ruang_kelas = formulir.cleaned_data["ruang_kelas"]
            subjects.save()
        return redirect("/story5")
    else:
        models.matkul.objects.filter(pk = pk).delete()
        form = forms.matakuliah()
        jadwal = models.matkul.objects.all()
        form_dict = {'formulir' : form,'jadwal' : jadwal}
    return render(request, 'jadwal.html', form_dict)

story4/templates/Profile.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel = "stylesheet" href = "{% static 'main.css' %}">
    </head>
    <body id="bg2">
        {% include 'navmenu.html' %}
        <div id="profpic">
            <img src="{% static 'CN40.jpg' %}" alt="" width = "250px", height = "350px">
        </div>

        <div class="profilebox">
            <b><i>About Reza:</i></b>
            <br>
            <b><i>Education History:</i></b>
            <ul>
                <li>SDN 08 Jatisampurna (2007-2011)</li>
                <li>SDN 03 Pondok Rangon Jakarta (2011-2013)</li>
                <li>SMPN 230 Jakarta (2013-2016)</li>
                <li>SMAN 99 Jakarta (2016-2019)</li>
                <li>Universitas Indonesia (2019-now)</li>
            </ul>
                <b><i>Skills</i></b>
            <ul>
                <li>PR(Professional Retard)</li>
                <li>PS(Professional Slacker)</li>
            </ul>
            <i>Tetap tryhard walaupun retard</i>
        </div>
        <button id = "button1" class="button">
            <a href="{% url 'story4:index' %}">
            <h2>Home</h2>
            </a>
        </button>
        
        <button id="button2" class="button">
            <a href="{% url 'story4:hobbies' %}">
            <h2>Hobbies</h2>
            </a>
        </button>
    
        <button id="comingsoon" class="button">
            <a href="{% url 'story4:comingsoon' %}">
                <h2>Coming soon</h2>
                </a>
        </button>

        <div class="sosmed">
            <div class="fb">
                <a href="https://www.facebook.com/muhammad.fahreza.33483/">
                <img src="{% static 'facebook.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="twit">
                <a href="">
                <img src="{% static 'twitter.svg' %}" alt="" height="50px" width="50px">
                </a>    
            </div>
            
            <div class="ig">
                <a href="instagram.com/r_reza00">
                <img src="{% static 'instagram.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="gitlab">
                <a href="https://gitlab.com/r_reza0">
                <img src="{% static 'logo.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
        </div>
        <div id="credit">
            Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
        </div>
    </body>
</html>

story4/templates/comingsoon.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel = "stylesheet" href = "{% static 'main.css' %}">
    </head>
    <body id="bg4">
        {% include 'navmenu.html' %}
        <div class = "welcome_box" id="kotak">
            <div id="coming-soon">
                <h1>You're not supposed to be here</h1>
                <br><br><br><br>
                <h4>but hey! here's something for You</h4>
                <a href="https://www.youtube.com/watch?v=ewaWUKsJ1Mo&ab_channel=bokensha">
                    <img src="gift.svg" alt="" height="50px" width="50px">
                </a>
            </div>
    </body>
</html>

story4/templates/hobbies.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel = "stylesheet" href = "{% static 'main.css' %}">
    </head>
    <body id="bg3">
        {% include 'navmenu.html' %}
        <div class="Hobbies">
            <h1>Hobbies and Interests</h1>
        </div>
        <div class="hobby">
            <div class="gaming">
                <h2>gaming</h2>
            </div>
            <div class="reading">
                <h2>reading</h2>
            </div>
            <div class="memeing">
                <h2>memeing</h2>
            </div>
            <div class="anime">
                <h2>anime</h2>
            </div>
        </div>

        <div class="hobby">
            <div class="gaming">
                <h3>Suka main game karena game itu asik <br>
                Ini game yang sering saya mainkan<h3>
                <img src="{% static 'capsule_616x353.jpg' %}" alt="" width = "275px" height = "250px">
            </div>
            <div class="reading">
                <h3>Suka baca manga karena wibu</h3>
                <img src="{% static 'bakuman.jpg' %}" alt="" width = "275px" height = "250px">
            </div>
            <div class="memeing">
                <img src="{% static '1441938.jpg' %}" alt="" width = "275px" height = "325px">
            </div>
            <div class="anime">
                <h3>Alesannya sama ama reading <br>
                btw hiratsuka sensei best girl</h3>
                <img src="{% static 'hiratsuka sensei.jpg' %}" alt="" width = "275px" height = "250px">
            </div>
        </div>

        <button id = "button1" class="button">
            <a href="{% url 'story4:Profile' %}">
            <h2>Profile</h2>
            </a>
        </button>
        
        <button id="button2" class="button">
            <a href="{% url 'story4:index' %}">
            <h2>home</h2>
            </a>
        </button>

        <button id="comingsoon" class="button">
            <a href="{% url 'story4:comingsoon' %}">
                <h2>Coming soon</h2>
                </a>
        </button>

        <div class="sosmed">
            <div class="fb">
                <a href="https://www.facebook.com/muhammad.fahreza.33483/">
                <img src="{% static 'facebook.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="twit">
                <a href="">
                <img src="{% static 'twitter.svg' %}" alt="" height="50px" width="50px">
                </a>    
            </div>
            
            <div class="ig">
                <a href="instagram.com/r_reza00">
                <img src="{% static 'instagram.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="gitlab">
                <a href="https://gitlab.com/r_reza0">
                <img src="{% static 'logo.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
        </div>
        <div id="credit">
            Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
        </div>
    </body>
</html>

story4/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel = "stylesheet" href = "{% static 'main.css' %}">
    </head>
    <body id = "bg1">
        {% include 'navmenu.html' %}
        <div class = "welcome_box">
            <div id="welcome-text">
                <h1>Welcome to the velvet room</h1>
            </div>
            <div id = "under">
                <p>currently under new management</p>
            </div>
        </div>
        <button id = "button1" class="button">
            <a href="{% url 'story4:Profile' %}">
            <h2>Profile</h2>
            </a>
        </button>
        
        <button id="button2" class="button">
            <a href="{% url 'story4:hobbies' %}">
            <h2>Hobbies</h2>
            </a>
        </button>

        <button id="comingsoon" class="button">
            <a href="{% url 'story4:comingsoon' %}">
                <h2>Coming soon</h2>
                </a>
        </button>

        <div class="sosmed">
            <div class="fb">
                <a href="https://www.facebook.com/muhammad.fahreza.33483/">
                <img src="{% static 'facebook.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="twit">
                <a href="">
                <img src="{% static 'twitter.svg' %}" alt="" height="50px" width="50px">
                </a>    
            </div>
            
            <div class="ig">
                <a href="instagram.com/r_reza00">
                <img src="{% static 'instagram.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
            <div class="gitlab">
                <a href="https://gitlab.com/r_reza0">
                <img src="{% static 'logo.svg' %}" alt="" height="50px" width="50px">
                </a>
            </div>
            
        </div>
        <div id="credit">
            Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
        </div>
    </body>
</html>

story4/templates/navmenu.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset = "utf-8">
        <title>navmenu</title>
        <meta name="viewport" content="width-device-width, initial-scale = 1.0">
        <link rel="stylesheet" href="{% static 'stylenav.css' %}"> 
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>
    <body>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars"></i>
            </label>
            <label class= "logo">Projects</label>
            <ul>
                <li><a class = "active" href="{% url 'story4:story1' %}">Story-1</a></li>
                <li><a class = "active" href="https://www.figma.com/file/xO1sv3HCDGAeEo7qogUaWE/Story-2-Prototype?node-id=7%3A3">Story-2</a></li>
                <li><a class = "active" href="{% url 'story4:index' %}">Story-3</a></li>
            </ul>
        </nav>
    </body>
</html>

story4/templates/story-1.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Selamat datang</title>
    
</head>
<body>
    {% include 'navmenu.html' %}
    <h1>Welcome...to webdev hell</h1>
    <br>
    <div>
        <img src="{% static 'CN40.jpg' %}" alt="pict error" width="200">
    </div>
    <br>
    <p><h3>M. Fahreza Pratama W.</h3></p>
    <b><i>Who am I?</i></b>
    <p>I study Computer Science in the Universitas Indonesia</p>

    <b><i>About Reza:</i></b>
    <ul>
        <li>Npm: 1906351051</li>
        <li>Maurt 2019</li>
    </ul>
    <b><i>Education History:</i></b>
    <ul>
        <li>SMPN 230 Jakarta (2013-2016)</li>
        <li>SMAN 99 Jakarta (2016-2019)</li>
        <li>Universitas Indonesia (2019-now)</li>
    </ul>
    <b>See my instagram:</b>
    <a href="https://instagram.com/r_reza00">
    <span>
        <img src="{% static 'instagram.svg' %}" alt="pict error" width="20">
    </span>
    </a>
</body>    

story5/templates/detail.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detail matkul</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>Nama Mata Kuliah</th>
                <th>Nama Dosen</th>
                <th>Jumlah SKS</th>
                <th>Deskripsi Mata Kuliah</th>
                <th>Tahun Semester</th>
                <th>Ruang Kelas</th>
            </tr>
        </thead>
        <tbody>
            <td>{{ jadwal.nama }}</td>
            <td>{{ jadwal.dosen }}</td>
            <td>{{ jadwal.SKS }}</td>
            <td>{{ jadwal.deskripsi }}</td>
            <td>{{ jadwal.sem_tahun }}</td>
            <td>{{ jadwal.ruang_kelas }}</td>
        </tbody>
    </table>
</body>
</html>

story5/templates/jadwal.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>jadwal matkul</title>
</head>
<body>
    <form method="POST" action="">
        {% csrf_token %}
        {{ formulir }}
        <input type="submit" value="Submit">
    </form>

    <table>
        <thead>
            <tr>
                <th>Nama Mata Kuliah</th>
            </tr>
        </thead>
        {% for i in jadwal %}
        <tbody>
            <td><a href="{% url 'story5:detail' pk=i.pk %}">{{ i.nama }}</a></td>
            <td> <a  href = "{% url 'story5:erase' pk=i.pk %}"><button class="btn btn-icon btn-danger" style="background-color: firebrick; color: white;">delete</button></a></td>
        </tbody>
        {% endfor %}
    </table>
</body>
</html>